// <auto-generated />
using System;
using DealerManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DealerManager.Infrastructure.Migrations
{
    [DbContext(typeof(DealerManagerDbContext))]
    [Migration("20260924111625_AddCandidateAskingPrice")]
    partial class AddCandidateAskingPrice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DealerManager.Domain.Entities.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AskingPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ExpectedSellingPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Mileage")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PurchasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Vin")
                        .HasColumnType("text");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("DealerManager.Domain.Entities.CandidateEstimate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ExpectedSellingPrice")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDecisionSnapshot")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("CandidateEstimates");
                });

            modelBuilder.Entity("DealerManager.Domain.Entities.CandidateEstimateItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateEstimateId")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("EstimatedAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CandidateEstimateId");

                    b.ToTable("CandidateEstimateItems");
                });

            modelBuilder.Entity("DealerManager.Domain.Entities.CandidatePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("CandidatePhotos");
                });

            modelBuilder.Entity("DealerManager.Domain.Entities.CapitalAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CapitalAccounts");
                });

            modelBuilder.Entity("DealerManager.Domain.Entities.FinancialTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("CapitalAccountId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CapitalAccountId");

                    b.HasIndex("VehicleId");

                    b.ToTable("FinancialTransactions");
                });

            modelBuilder.Entity("DealerManager.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Mileage")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SourceCandidateId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Vin")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceCandidateId")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("DealerManager.Domain.Entities.VehicleCostPlanItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CommittedAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CurrentEstimatedAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleCostPlanItems");
                });

            modelBuilder.Entity("DealerManager.Domain.Entities.VehicleExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int?>("CostPlanItemId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("text");

                    b.Property<int>("FinancialTransactionId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Supplier")
                        .HasColumnType("text");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CostPlanItemId");

                    b.HasIndex("FinancialTransactionId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleExpenses");
                });

            modelBuilder.Entity("DealerManager.Domain.Entities.VehicleSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("FinancialTransactionId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("SoldAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FinancialTransactionId");

                    b.HasIndex("VehicleId")
                        .IsUnique();

                    b.ToTable("VehicleSales");
                });

            modelBuilder.Entity("DealerManager.Domain.Entities.VehicleStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("FromStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleStatusHistories");
                });

            modelBuilder.Entity("DealerManager.Domain.Entities.CandidateEstimate", b =>
                {
                    b.HasOne("DealerManager.Domain.Entities.Candidate", "Candidate")
                        .WithMany("CandidateEstimates")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("DealerManager.Domain.Entities.CandidateEstimateItem", b =>
                {
                    b.HasOne("DealerManager.Domain.Entities.CandidateEstimate", "CandidateEstimate")
                        .WithMany("CandidateEstimateItems")
                        .HasForeignKey("CandidateEstimateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CandidateEstimate");
                });

            modelBuilder.Entity("DealerManager.Domain.Entities.CandidatePhoto", b =>
                {
                    b.HasOne("DealerManager.Domain.Entities.Candidate", "Candidate")
                        .WithMany("CandidatePhotos")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("DealerManager.Domain.Entities.FinancialTransaction", b =>
                {
                    b.HasOne("DealerManager.Domain.Entities.CapitalAccount", "CapitalAccount")
                        .WithMany("FinancialTransactions")
                        .HasForeignKey("CapitalAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealerManager.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId");

                    b.Navigation("CapitalAccount");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DealerManager.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("DealerManager.Domain.Entities.Candidate", "SourceCandidate")
                        .WithOne("Vehicle")
                        .HasForeignKey("DealerManager.Domain.Entities.Vehicle", "SourceCandidateId");

                    b.Navigation("SourceCandidate");
                });

            modelBuilder.Entity("DealerManager.Domain.Entities.VehicleCostPlanItem", b =>
                {
                    b.HasOne("DealerManager.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleCostPlanItems")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DealerManager.Domain.Entities.VehicleExpense", b =>
                {
                    b.HasOne("DealerManager.Domain.Entities.VehicleCostPlanItem", "CostPlanItem")
                        .WithMany("VehicleExpenses")
                        .HasForeignKey("CostPlanItemId");

                    b.HasOne("DealerManager.Domain.Entities.FinancialTransaction", "FinancialTransaction")
                        .WithMany()
                        .HasForeignKey("FinancialTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealerManager.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleExpenses")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CostPlanItem");

                    b.Navigation("FinancialTransaction");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DealerManager.Domain.Entities.VehicleSale", b =>
                {
                    b.HasOne("DealerManager.Domain.Entities.FinancialTransaction", "FinancialTransaction")
                        .WithMany()
                        .HasForeignKey("FinancialTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealerManager.Domain.Entities.Vehicle", "Vehicle")
                        .WithOne("VehicleSale")
                        .HasForeignKey("DealerManager.Domain.Entities.VehicleSale", "VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FinancialTransaction");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DealerManager.Domain.Entities.VehicleStatusHistory", b =>
                {
                    b.HasOne("DealerManager.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleStatusHistory")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DealerManager.Domain.Entities.Candidate", b =>
                {
                    b.Navigation("CandidateEstimates");

                    b.Navigation("CandidatePhotos");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DealerManager.Domain.Entities.CandidateEstimate", b =>
                {
                    b.Navigation("CandidateEstimateItems");
                });

            modelBuilder.Entity("DealerManager.Domain.Entities.CapitalAccount", b =>
                {
                    b.Navigation("FinancialTransactions");
                });

            modelBuilder.Entity("DealerManager.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("VehicleCostPlanItems");

                    b.Navigation("VehicleExpenses");

                    b.Navigation("VehicleSale");

                    b.Navigation("VehicleStatusHistory");
                });

            modelBuilder.Entity("DealerManager.Domain.Entities.VehicleCostPlanItem", b =>
                {
                    b.Navigation("VehicleExpenses");
                });
#pragma warning restore 612, 618
        }
    }
}
