<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Entities/" />
    <Folder Include="Common/" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DealerManager.Common\DealerManager.Common.csproj" />
  </ItemGroup>
</Project>
